name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Extrair aplicativo
        run: |
          unzip -o app-transportadora.zip -d app-extraido
          find app-extraido -maxdepth 3 -type f

      - name: Compilar aplicativo
        run: |
          cd app-extraido
          chmod +x gradlew
          ./gradlew assembleDebug
